name: test

on: workflow_dispatch

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Slither analysis on Solidity files
        uses: crytic/slither-action@v0.4.0
        with:
          ignore-compile: true

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --root packages/zksync-storage-contracts
        id: test

      - name: Echidna scan on StorageProofVerifier
        uses: crytic/echidna-action@v2
        with:
          files: StorageProofVerifier
          contract: packages/zksync-storage-contracts

      - name: Echidna scan on SparseMerkleTree
        uses: crytic/echidna-action@v2
        with:
          files: SparseMerkleTree
          contract: packages/zksync-storage-contracts

      - name: Echidna scan on Blake2S
        uses: crytic/echidna-action@v2
        with:
          files: Blake2S
          contract: packages/zksync-storage-contracts

      - name: Echidna scan on RegistryResolver
        uses: crytic/echidna-action@v2
        with:
          files: RegistryResolver
          contract: packages/zksync-storage-contracts